# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/UI_Files/StudentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 361, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.infoWidget = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.infoWidget.setContentsMargins(0, 0, 0, 0)
        self.infoWidget.setSpacing(2)
        self.infoWidget.setObjectName("infoWidget")
        self.videoWidget = QtWidgets.QHBoxLayout()
        self.videoWidget.setObjectName("videoWidget")
        self.Video = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.Video.setObjectName("Video")
        self.videoWidget.addWidget(self.Video)
        self.infoWidget.addLayout(self.videoWidget)
        self.buttomWidget = QtWidgets.QHBoxLayout()
        self.buttomWidget.setContentsMargins(20, -1, 20, -1)
        self.buttomWidget.setObjectName("buttomWidget")
        self.startButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.buttomWidget.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.buttomWidget.addWidget(self.stopButton)
        self.recordButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.recordButton.setObjectName("recordButton")
        self.buttomWidget.addWidget(self.recordButton)
        self.infoWidget.addLayout(self.buttomWidget)
        self.infoWidget.setStretch(0, 4)
        self.infoWidget.setStretch(1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(19, 360, 361, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.DebugWidget = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.DebugWidget.setContentsMargins(0, 0, 0, 0)
        self.DebugWidget.setObjectName("DebugWidget")
        self.DebugMessage = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.DebugMessage.setObjectName("DebugMessage")
        self.DebugWidget.addWidget(self.DebugMessage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.recordButton.setText(_translate("MainWindow", "Record"))
